[project]
name = "ai-insurance-claim-processor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "notebook>=7.4.7",
    "openai>=2.7.2",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
